package responses

type UsdtTrxBalance struct {
	Balance string `json:"balance"`
}

type Withdraw struct {
	Success    bool  `json:"success"`
	WithdrawID int64 `json:"withdraw_id"`
	Status     int   `json:"status"`
}

type Currency struct {
	ID              string     `json:"id"`
	Symbol          string     `json:"symbol"`
	Name            string     `json:"name"`
	WebSlug         string     `json:"web_slug"`
	AssetPlatformID string     `json:"asset_platform_id"`
	MarketData      MarketData `json:"market_data"`
}

type MarketData struct {
	CurrentPrice              CurrentPrice             `json:"current_price"`
	MarketCap                 MarketCap                `json:"market_cap"`
	High24H                   High24H                  `json:"high_24h"`
	Low24H                    Low24H                   `json:"low_24h"`
	PriceChange24H            float64                  `json:"price_change_24h"`
	PriceChangePercentage24H  float64                  `json:"price_change_percentage_24h"`
	PriceChangePercentage7D   float64                  `json:"price_change_percentage_7d"`
	PriceChangePercentage14D  float64                  `json:"price_change_percentage_14d"`
	PriceChangePercentage30D  float64                  `json:"price_change_percentage_30d"`
	PriceChangePercentage60D  float64                  `json:"price_change_percentage_60d"`
	PriceChangePercentage200D float64                  `json:"price_change_percentage_200d"`
	PriceChangePercentage1Y   float64                  `json:"price_change_percentage_1y"`
	PriceChange24HInCurrency  PriceChange24HInCurrency `json:"price_change_24h_in_currency"`
}

type CurrentPrice struct {
	Aed  float64 `json:"aed"`
	Ars  float64 `json:"ars"`
	Aud  float64 `json:"aud"`
	Bch  float64 `json:"bch"`
	Bdt  float64 `json:"bdt"`
	Bhd  float64 `json:"bhd"`
	Bmd  float64 `json:"bmd"`
	Bnb  float64 `json:"bnb"`
	Brl  float64 `json:"brl"`
	Btc  float64 `json:"btc"`
	Cad  float64 `json:"cad"`
	Chf  float64 `json:"chf"`
	Clp  float64 `json:"clp"`
	Cny  float64 `json:"cny"`
	Dkk  float64 `json:"dkk"`
	Eth  float64 `json:"eth"`
	Eur  float64 `json:"eur"`
	Gbp  float64 `json:"gbp"`
	Hkd  float64 `json:"hkd"`
	Huf  float64 `json:"huf"`
	Idr  float64 `json:"idr"`
	Ils  float64 `json:"ils"`
	Inr  float64 `json:"inr"`
	Jpy  float64 `json:"jpy"`
	Krw  float64 `json:"krw"`
	Kwd  float64 `json:"kwd"`
	Lkr  float64 `json:"lkr"`
	Ltc  float64 `json:"ltc"`
	Mmk  float64 `json:"mmk"`
	Mxn  float64 `json:"mxn"`
	Myr  float64 `json:"myr"`
	Ngn  float64 `json:"ngn"`
	Nok  float64 `json:"nok"`
	Nzd  float64 `json:"nzd"`
	Php  float64 `json:"php"`
	Pkr  float64 `json:"pkr"`
	Pln  float64 `json:"pln"`
	Rub  float64 `json:"rub"`
	Sar  float64 `json:"sar"`
	Sek  float64 `json:"sek"`
	Sgd  float64 `json:"sgd"`
	Thb  float64 `json:"thb"`
	Try  float64 `json:"try"`
	Twd  float64 `json:"twd"`
	Uah  float64 `json:"uah"`
	Usd  float64 `json:"usd"`
	Vef  float64 `json:"vef"`
	Vnd  float64 `json:"vnd"`
	Xag  float64 `json:"xag"`
	Xau  float64 `json:"xau"`
	Xdr  float64 `json:"xdr"`
	Xlm  float64 `json:"xlm"`
	Xrp  float64 `json:"xrp"`
	Yfi  float64 `json:"yfi"`
	Zar  float64 `json:"zar"`
	Bits float64 `json:"bits"`
	Link float64 `json:"link"`
	Sats float64 `json:"sats"`
}

type MarketCap struct {
	Aed  int64 `json:"aed"`
	Ars  int64 `json:"ars"`
	Aud  int64 `json:"aud"`
	Bch  int64 `json:"bch"`
	Bdt  int64 `json:"bdt"`
	Bhd  int64 `json:"bhd"`
	Bmd  int64 `json:"bmd"`
	Bnb  int64 `json:"bnb"`
	Brl  int64 `json:"brl"`
	Btc  int64 `json:"btc"`
	Cad  int64 `json:"cad"`
	Chf  int64 `json:"chf"`
	Clp  int64 `json:"clp"`
	Cny  int64 `json:"cny"`
	Czk  int64 `json:"czk"`
	Dkk  int64 `json:"dkk"`
	Dot  int64 `json:"dot"`
	Eos  int64 `json:"eos"`
	Eth  int64 `json:"eth"`
	Eur  int64 `json:"eur"`
	Gbp  int64 `json:"gbp"`
	Gel  int64 `json:"gel"`
	Hkd  int64 `json:"hkd"`
	Huf  int64 `json:"huf"`
	Idr  int64 `json:"idr"`
	Ils  int64 `json:"ils"`
	Inr  int64 `json:"inr"`
	Jpy  int64 `json:"jpy"`
	Krw  int64 `json:"krw"`
	Kwd  int64 `json:"kwd"`
	Lkr  int64 `json:"lkr"`
	Ltc  int64 `json:"ltc"`
	Mmk  int64 `json:"mmk"`
	Mxn  int64 `json:"mxn"`
	Myr  int64 `json:"myr"`
	Ngn  int64 `json:"ngn"`
	Nok  int64 `json:"nok"`
	Nzd  int64 `json:"nzd"`
	Php  int64 `json:"php"`
	Pkr  int64 `json:"pkr"`
	Pln  int64 `json:"pln"`
	Rub  int64 `json:"rub"`
	Sar  int64 `json:"sar"`
	Sek  int64 `json:"sek"`
	Sgd  int64 `json:"sgd"`
	Thb  int64 `json:"thb"`
	Try  int64 `json:"try"`
	Twd  int64 `json:"twd"`
	Uah  int64 `json:"uah"`
	Usd  int64 `json:"usd"`
	Vef  int64 `json:"vef"`
	Vnd  int64 `json:"vnd"`
	Xag  int64 `json:"xag"`
	Xau  int64 `json:"xau"`
	Xdr  int64 `json:"xdr"`
	Xlm  int64 `json:"xlm"`
	Xrp  int64 `json:"xrp"`
	Yfi  int64 `json:"yfi"`
	Zar  int64 `json:"zar"`
	Bits int64 `json:"bits"`
	Link int64 `json:"link"`
	Sats int64 `json:"sats"`
}

type High24H struct {
	Aed  float64 `json:"aed"`
	Ars  float64 `json:"ars"`
	Aud  float64 `json:"aud"`
	Bch  float64 `json:"bch"`
	Bdt  float64 `json:"bdt"`
	Bhd  float64 `json:"bhd"`
	Bmd  float64 `json:"bmd"`
	Bnb  float64 `json:"bnb"`
	Brl  float64 `json:"brl"`
	Btc  float64 `json:"btc"`
	Cad  float64 `json:"cad"`
	Chf  float64 `json:"chf"`
	Clp  float64 `json:"clp"`
	Cny  float64 `json:"cny"`
	Czk  float64 `json:"czk"`
	Dkk  float64 `json:"dkk"`
	Dot  float64 `json:"dot"`
	Eos  float64 `json:"eos"`
	Eth  float64 `json:"eth"`
	Eur  float64 `json:"eur"`
	Gbp  float64 `json:"gbp"`
	Gel  float64 `json:"gel"`
	Hkd  float64 `json:"hkd"`
	Huf  float64 `json:"huf"`
	Idr  float64 `json:"idr"`
	Ils  float64 `json:"ils"`
	Inr  float64 `json:"inr"`
	Jpy  float64 `json:"jpy"`
	Krw  float64 `json:"krw"`
	Kwd  float64 `json:"kwd"`
	Lkr  float64 `json:"lkr"`
	Ltc  float64 `json:"ltc"`
	Mmk  float64 `json:"mmk"`
	Mxn  float64 `json:"mxn"`
	Myr  float64 `json:"myr"`
	Ngn  float64 `json:"ngn"`
	Nok  float64 `json:"nok"`
	Nzd  float64 `json:"nzd"`
	Php  float64 `json:"php"`
	Pkr  float64 `json:"pkr"`
	Pln  float64 `json:"pln"`
	Rub  float64 `json:"rub"`
	Sar  float64 `json:"sar"`
	Sek  float64 `json:"sek"`
	Sgd  float64 `json:"sgd"`
	Thb  float64 `json:"thb"`
	Try  float64 `json:"try"`
	Twd  float64 `json:"twd"`
	Uah  float64 `json:"uah"`
	Usd  float64 `json:"usd"`
	Vef  float64 `json:"vef"`
	Vnd  float64 `json:"vnd"`
	Xag  float64 `json:"xag"`
	Xau  float64 `json:"xau"`
	Xdr  float64 `json:"xdr"`
	Xlm  float64 `json:"xlm"`
	Xrp  float64 `json:"xrp"`
	Yfi  float64 `json:"yfi"`
	Zar  float64 `json:"zar"`
	Bits float64 `json:"bits"`
	Link float64 `json:"link"`
	Sats float64 `json:"sats"`
}

type Low24H struct {
	Aed  float64 `json:"aed"`
	Ars  float64 `json:"ars"`
	Aud  float64 `json:"aud"`
	Bch  float64 `json:"bch"`
	Bdt  float64 `json:"bdt"`
	Bhd  float64 `json:"bhd"`
	Bmd  float64 `json:"bmd"`
	Bnb  float64 `json:"bnb"`
	Brl  float64 `json:"brl"`
	Btc  float64 `json:"btc"`
	Cad  float64 `json:"cad"`
	Chf  float64 `json:"chf"`
	Clp  float64 `json:"clp"`
	Cny  float64 `json:"cny"`
	Czk  float64 `json:"czk"`
	Dkk  float64 `json:"dkk"`
	Dot  float64 `json:"dot"`
	Eos  float64 `json:"eos"`
	Eth  float64 `json:"eth"`
	Eur  float64 `json:"eur"`
	Gbp  float64 `json:"gbp"`
	Gel  float64 `json:"gel"`
	Hkd  float64 `json:"hkd"`
	Huf  float64 `json:"huf"`
	Idr  float64 `json:"idr"`
	Ils  float64 `json:"ils"`
	Inr  float64 `json:"inr"`
	Jpy  float64 `json:"jpy"`
	Krw  float64 `json:"krw"`
	Kwd  float64 `json:"kwd"`
	Lkr  float64 `json:"lkr"`
	Ltc  float64 `json:"ltc"`
	Mmk  float64 `json:"mmk"`
	Mxn  float64 `json:"mxn"`
	Myr  float64 `json:"myr"`
	Ngn  float64 `json:"ngn"`
	Nok  float64 `json:"nok"`
	Nzd  float64 `json:"nzd"`
	Php  float64 `json:"php"`
	Pkr  float64 `json:"pkr"`
	Pln  float64 `json:"pln"`
	Rub  float64 `json:"rub"`
	Sar  float64 `json:"sar"`
	Sek  float64 `json:"sek"`
	Sgd  float64 `json:"sgd"`
	Thb  float64 `json:"thb"`
	Try  float64 `json:"try"`
	Twd  float64 `json:"twd"`
	Uah  float64 `json:"uah"`
	Usd  float64 `json:"usd"`
	Vef  float64 `json:"vef"`
	Vnd  float64 `json:"vnd"`
	Xag  float64 `json:"xag"`
	Xau  float64 `json:"xau"`
	Xdr  float64 `json:"xdr"`
	Xlm  float64 `json:"xlm"`
	Xrp  float64 `json:"xrp"`
	Yfi  float64 `json:"yfi"`
	Zar  float64 `json:"zar"`
	Bits float64 `json:"bits"`
	Link float64 `json:"link"`
	Sats float64 `json:"sats"`
}

type PriceChange24HInCurrency struct {
	Aed  float64 `json:"aed"`
	Ars  float64 `json:"ars"`
	Aud  float64 `json:"aud"`
	Bch  float64 `json:"bch"`
	Bdt  float64 `json:"bdt"`
	Bhd  float64 `json:"bhd"`
	Bmd  float64 `json:"bmd"`
	Bnb  float64 `json:"bnb"`
	Brl  float64 `json:"brl"`
	Btc  float64 `json:"btc"`
	Cad  float64 `json:"cad"`
	Chf  float64 `json:"chf"`
	Clp  float64 `json:"clp"`
	Cny  float64 `json:"cny"`
	Czk  float64 `json:"czk"`
	Dkk  float64 `json:"dkk"`
	Dot  float64 `json:"dot"`
	Eos  float64 `json:"eos"`
	Eth  float64 `json:"eth"`
	Eur  float64 `json:"eur"`
	Gbp  float64 `json:"gbp"`
	Gel  float64 `json:"gel"`
	Hkd  float64 `json:"hkd"`
	Huf  float64 `json:"huf"`
	Idr  float64 `json:"idr"`
	Ils  float64 `json:"ils"`
	Inr  float64 `json:"inr"`
	Jpy  float64 `json:"jpy"`
	Krw  float64 `json:"krw"`
	Kwd  float64 `json:"kwd"`
	Lkr  float64 `json:"lkr"`
	Ltc  float64 `json:"ltc"`
	Mmk  float64 `json:"mmk"`
	Mxn  float64 `json:"mxn"`
	Myr  float64 `json:"myr"`
	Ngn  float64 `json:"ngn"`
	Nok  float64 `json:"nok"`
	Nzd  float64 `json:"nzd"`
	Php  float64 `json:"php"`
	Pkr  float64 `json:"pkr"`
	Pln  float64 `json:"pln"`
	Rub  float64 `json:"rub"`
	Sar  float64 `json:"sar"`
	Sek  float64 `json:"sek"`
	Sgd  float64 `json:"sgd"`
	Thb  float64 `json:"thb"`
	Try  float64 `json:"try"`
	Twd  float64 `json:"twd"`
	Uah  float64 `json:"uah"`
	Usd  float64 `json:"usd"`
	Vef  float64 `json:"vef"`
	Vnd  float64 `json:"vnd"`
	Xag  float64 `json:"xag"`
	Xau  float64 `json:"xau"`
	Xdr  float64 `json:"xdr"`
	Xlm  float64 `json:"xlm"`
	Xrp  float64 `json:"xrp"`
	Yfi  float64 `json:"yfi"`
	Zar  float64 `json:"zar"`
	Bits float64 `json:"bits"`
	Link float64 `json:"link"`
	Sats float64 `json:"sats"`
}
